//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4payeSystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities3 : DbContext
    {
        public Entities3()
            : base("name=Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblForooshgah> TblForooshgahs { get; set; }
        public virtual DbSet<TblKomod> TblKomods { get; set; }
        public virtual DbSet<TblTarakonesh> TblTarakoneshes { get; set; }
        public virtual DbSet<TblUser> TblUsers { get; set; }
        public virtual DbSet<TblCreditor> TblCreditors { get; set; }
        public virtual DbSet<TblDebtor> TblDebtors { get; set; }
        public virtual DbSet<TblPurchaseRecord> TblPurchaseRecords { get; set; }
        public virtual DbSet<TblBuy> TblBuys { get; set; }
        public virtual DbSet<TblBuyKala> TblBuyKalas { get; set; }
        public virtual DbSet<StorePTblurchas> StorePTblurchases { get; set; }
    }
}
