//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4payeSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBuyKala
    {
        public int Record { get; set; }
        public int ID { get; set; }
        public string Name_kala { get; set; }
        public int Number { get; set; }
        public long Price { get; set; }
        public string SerialBuy { get; set; }
    }
}
