//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4payeSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBuy
    {
        public int Record { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public long Price { get; set; }
        public System.DateTime DateTime_Buy { get; set; }
        public int Installments { get; set; }
        public string Type_Buy { get; set; }
        public Nullable<long> Prepayment { get; set; }
        public string Check_number1 { get; set; }
        public Nullable<System.DateTime> Date_Check1 { get; set; }
        public string Check_number2 { get; set; }
        public Nullable<System.DateTime> Date_Check2 { get; set; }
        public string Check_number3 { get; set; }
        public Nullable<System.DateTime> Date_Check3 { get; set; }
        public string Check_number4 { get; set; }
        public Nullable<System.DateTime> Date_Check4 { get; set; }
        public string Check_number5 { get; set; }
        public Nullable<System.DateTime> Date_Check5 { get; set; }
        public string Check_number6 { get; set; }
        public Nullable<System.DateTime> Date_Check6 { get; set; }
        public string SerialBuy { get; set; }
    }
}
