//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4payeSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblForooshgah
    {
        public int ID { get; set; }
        public string KalaName { get; set; }
        public string Price { get; set; }
        public string Mojudi { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
    }
}
